version: '3'

services:
  # Angular App
  app:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm start hr -- --host 0.0.0.0 --port 4200 --disableHostCheck=true
    ports:
      - '4200:4200'

  # Express App
  api:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    expose:
      - 4200
    command: npm run start api
    ports:
      - 3333:3333

volumes:
  mono-node-modules: null
